import deepmerge from 'deepmerge'

import { buildApprovalsFor, isCatalogName, NODE_CATALOG } from '../catalog/node'
import { TYPE_PAIRS } from '../catalog/pairs'
import { ResolutionError } from '../errors'
import { CLI_PACKAGE } from './manifest'
import type { DevstackModule } from '../types/module'
import type { DependencyMap, PackageJson } from '../types/package-json'
import { formatDiagnostics, resolveStack } from './resolver/index'

export interface CompositionResult {
  orderedModules: DevstackModule[]
  packageJson: PackageJson
  /** Packages whose install scripts the package manager must be allowed to run (pnpm). */
  buildApprovals: string[]
}

interface DependencyNames {
  dependencies: Map<string, string>
  devDependencies: Map<string, string>
}

/** Collects package names per dependency type, remembering the first module that asked for each. */
function collectDependencyNames(modules: DevstackModule[]): DependencyNames {
  const dependencies = new Map<string, string>()
  const devDependencies = new Map<string, string>()
  for (const moduleDefinition of modules) {
    for (const name of moduleDefinition.dependencies ?? []) {
      if (!dependencies.has(name)) dependencies.set(name, moduleDefinition.id)
    }
    for (const name of moduleDefinition.devDependencies ?? []) {
      if (!devDependencies.has(name)) devDependencies.set(name, moduleDefinition.id)
    }
  }
  for (const name of dependencies.keys()) {
    devDependencies.delete(name)
  }
  for (const [runtime, types] of TYPE_PAIRS) {
    if (dependencies.has(runtime) && !dependencies.has(types) && !devDependencies.has(types)) {
      devDependencies.set(types, `type pair of ${runtime}`)
    }
  }
  return { dependencies, devDependencies }
}

function toVersionMap(names: Map<string, string>): DependencyMap {
  const entries = [...names.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, owner]): [string, string] => {
      if (!isCatalogName(name)) {
        throw new ResolutionError(`"${name}" (required by ${owner}) is not in the version catalog`)
      }
      return [name, NODE_CATALOG[name].version]
    })
  return Object.fromEntries(entries)
}

export function composeProjectPackageJson(
  projectName: string,
  modules: DevstackModule[]
): PackageJson {
  const basePackageJson: PackageJson = {
    name: projectName,
    version: '0.1.0',
    private: true,
    description: `Generated by ${CLI_PACKAGE.name}`,
    scripts: {
      build: 'tsc -p tsconfig.json'
    }
  }

  const withFragments = modules.reduce<PackageJson>(
    (accumulator, moduleDefinition) =>
      deepmerge(accumulator, moduleDefinition.packageJson ?? {}) as PackageJson,
    basePackageJson
  )

  const names = collectDependencyNames(modules)
  return {
    ...withFragments,
    dependencies: toVersionMap(names.dependencies),
    devDependencies: toVersionMap(names.devDependencies)
  }
}

export function composeModules(
  selectedModuleNames: string[],
  registry: Map<string, DevstackModule>,
  projectName: string
): CompositionResult {
  const resolution = resolveStack(selectedModuleNames, registry)
  const errors = resolution.diagnostics.filter((diagnostic) => diagnostic.severity === 'error')
  if (errors.length > 0) {
    throw new ResolutionError(formatDiagnostics(resolution.diagnostics), {
      diagnostics: resolution.diagnostics
    })
  }
  const orderedModules = resolution.modules

  const packageJson = composeProjectPackageJson(projectName, orderedModules)
  const installed = [
    ...Object.keys(packageJson.dependencies ?? {}),
    ...Object.keys(packageJson.devDependencies ?? {})
  ]
  return { orderedModules, packageJson, buildApprovals: buildApprovalsFor(installed) }
}
