import deepmerge from 'deepmerge'

import { ResolutionError } from '../errors'

import type { DevstackModule } from '../types/module'
import type { DependencyMap, PackageJson } from '../types/package-json'
import { validateModuleSelection } from './validator'

export interface CompositionResult {
  orderedModules: DevstackModule[]
  packageJson: PackageJson
}

function resolveModulesInDependencyOrder(
  selectedModuleNames: string[],
  registry: Map<string, DevstackModule>
): DevstackModule[] {
  const visited = new Set<string>()
  const visiting = new Set<string>()
  const ordered: DevstackModule[] = []

  const visit = (moduleName: string): void => {
    if (visited.has(moduleName)) {
      return
    }

    if (visiting.has(moduleName)) {
      throw new ResolutionError(`Circular module requirement detected at "${moduleName}"`)
    }

    const moduleDefinition = registry.get(moduleName)
    if (!moduleDefinition) {
      throw new ResolutionError(`Unknown module requested: "${moduleName}"`)
    }

    visiting.add(moduleName)
    for (const required of moduleDefinition.requires ?? []) {
      visit(required)
    }
    visiting.delete(moduleName)

    visited.add(moduleName)
    ordered.push(moduleDefinition)
  }

  for (const selectedModule of selectedModuleNames) {
    visit(selectedModule)
  }

  return ordered
}

function mergeDependencyMaps(
  target: DependencyMap,
  incoming: DependencyMap,
  owner: string,
  owners: Map<string, { version: string; owner: string; type: 'dependencies' | 'devDependencies' }>,
  dependencyType: 'dependencies' | 'devDependencies'
): void {
  for (const [packageName, version] of Object.entries(incoming)) {
    const existing = owners.get(packageName)
    if (existing && existing.version !== version) {
      throw new ResolutionError(
        `Dependency version conflict for "${packageName}": "${existing.version}" (${existing.owner}) vs "${version}" (${owner})`
      )
    }

    owners.set(packageName, { version, owner, type: dependencyType })
    target[packageName] = version
  }
}

export function composeProjectPackageJson(
  projectName: string,
  modules: DevstackModule[]
): PackageJson {
  const basePackageJson: PackageJson = {
    name: projectName,
    version: '0.1.0',
    private: true,
    description: `Generated by create-devstack`,
    scripts: {
      build: 'tsc -p tsconfig.json'
    },
    dependencies: {},
    devDependencies: {}
  }

  const withFragments = modules.reduce<PackageJson>(
    (accumulator, moduleDefinition) =>
      deepmerge(accumulator, moduleDefinition.packageJson ?? {}) as PackageJson,
    basePackageJson
  )

  const dependencies: DependencyMap = { ...(withFragments.dependencies ?? {}) }
  const devDependencies: DependencyMap = { ...(withFragments.devDependencies ?? {}) }

  const owners = new Map<
    string,
    { version: string; owner: string; type: 'dependencies' | 'devDependencies' }
  >()

  mergeDependencyMaps(dependencies, dependencies, 'packageJson fragments', owners, 'dependencies')
  mergeDependencyMaps(
    devDependencies,
    devDependencies,
    'packageJson fragments',
    owners,
    'devDependencies'
  )

  for (const moduleDefinition of modules) {
    mergeDependencyMaps(
      dependencies,
      moduleDefinition.dependencies ?? {},
      moduleDefinition.name,
      owners,
      'dependencies'
    )
    mergeDependencyMaps(
      devDependencies,
      moduleDefinition.devDependencies ?? {},
      moduleDefinition.name,
      owners,
      'devDependencies'
    )
  }

  for (const [dependencyName, dependencyVersion] of Object.entries(dependencies)) {
    const devDependencyVersion = devDependencies[dependencyName]
    if (!devDependencyVersion) {
      continue
    }

    if (devDependencyVersion !== dependencyVersion) {
      throw new ResolutionError(
        `Dependency "${dependencyName}" appears in both dependencies and devDependencies with different versions`
      )
    }

    delete devDependencies[dependencyName]
  }

  return {
    ...withFragments,
    dependencies,
    devDependencies
  }
}

export function composeModules(
  selectedModuleNames: string[],
  registry: Map<string, DevstackModule>,
  projectName: string
): CompositionResult {
  const orderedModules = resolveModulesInDependencyOrder(selectedModuleNames, registry)
  validateModuleSelection(orderedModules)

  return {
    orderedModules,
    packageJson: composeProjectPackageJson(projectName, orderedModules)
  }
}
