import deepmerge from 'deepmerge'

import { buildApprovalsFor, isCatalogName, NODE_CATALOG } from '../catalog/node'
import { TYPE_PAIRS } from '../catalog/pairs'
import { ResolutionError } from '../errors'
import { CLI_PACKAGE } from './manifest'
import type { DevstackModule } from '../types/module'
import type { DependencyMap, PackageJson } from '../types/package-json'
import { validateModuleSelection } from './validator'

export interface CompositionResult {
  orderedModules: DevstackModule[]
  packageJson: PackageJson
  /** Packages whose install scripts the package manager must be allowed to run (pnpm). */
  buildApprovals: string[]
}

function resolveModulesInDependencyOrder(
  selectedModuleNames: string[],
  registry: Map<string, DevstackModule>
): DevstackModule[] {
  const visited = new Set<string>()
  const visiting = new Set<string>()
  const ordered: DevstackModule[] = []

  const visit = (moduleName: string): void => {
    if (visited.has(moduleName)) {
      return
    }

    if (visiting.has(moduleName)) {
      throw new ResolutionError(`Circular module requirement detected at "${moduleName}"`)
    }

    const moduleDefinition = registry.get(moduleName)
    if (!moduleDefinition) {
      throw new ResolutionError(`Unknown module requested: "${moduleName}"`)
    }

    visiting.add(moduleName)
    for (const required of moduleDefinition.requires ?? []) {
      visit(required)
    }
    visiting.delete(moduleName)

    visited.add(moduleName)
    ordered.push(moduleDefinition)
  }

  for (const selectedModule of selectedModuleNames) {
    visit(selectedModule)
  }

  return ordered
}

interface DependencyNames {
  dependencies: Map<string, string>
  devDependencies: Map<string, string>
}

/** Collects package names per dependency type, remembering the first module that asked for each. */
function collectDependencyNames(modules: DevstackModule[]): DependencyNames {
  const dependencies = new Map<string, string>()
  const devDependencies = new Map<string, string>()
  for (const moduleDefinition of modules) {
    for (const name of moduleDefinition.dependencies ?? []) {
      if (!dependencies.has(name)) dependencies.set(name, moduleDefinition.name)
    }
    for (const name of moduleDefinition.devDependencies ?? []) {
      if (!devDependencies.has(name)) devDependencies.set(name, moduleDefinition.name)
    }
  }
  for (const name of dependencies.keys()) {
    devDependencies.delete(name)
  }
  for (const [runtime, types] of TYPE_PAIRS) {
    if (dependencies.has(runtime) && !dependencies.has(types) && !devDependencies.has(types)) {
      devDependencies.set(types, `type pair of ${runtime}`)
    }
  }
  return { dependencies, devDependencies }
}

function toVersionMap(names: Map<string, string>): DependencyMap {
  const entries = [...names.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, owner]): [string, string] => {
      if (!isCatalogName(name)) {
        throw new ResolutionError(`"${name}" (required by ${owner}) is not in the version catalog`)
      }
      return [name, NODE_CATALOG[name].version]
    })
  return Object.fromEntries(entries)
}

export function composeProjectPackageJson(
  projectName: string,
  modules: DevstackModule[]
): PackageJson {
  const basePackageJson: PackageJson = {
    name: projectName,
    version: '0.1.0',
    private: true,
    description: `Generated by ${CLI_PACKAGE.name}`,
    scripts: {
      build: 'tsc -p tsconfig.json'
    }
  }

  const withFragments = modules.reduce<PackageJson>(
    (accumulator, moduleDefinition) =>
      deepmerge(accumulator, moduleDefinition.packageJson ?? {}) as PackageJson,
    basePackageJson
  )

  const names = collectDependencyNames(modules)
  return {
    ...withFragments,
    dependencies: toVersionMap(names.dependencies),
    devDependencies: toVersionMap(names.devDependencies)
  }
}

export function composeModules(
  selectedModuleNames: string[],
  registry: Map<string, DevstackModule>,
  projectName: string
): CompositionResult {
  const orderedModules = resolveModulesInDependencyOrder(selectedModuleNames, registry)
  validateModuleSelection(orderedModules)

  const packageJson = composeProjectPackageJson(projectName, orderedModules)
  const installed = [
    ...Object.keys(packageJson.dependencies ?? {}),
    ...Object.keys(packageJson.devDependencies ?? {})
  ]
  return { orderedModules, packageJson, buildApprovals: buildApprovalsFor(installed) }
}
