import { access, readFile } from 'node:fs/promises'
import path from 'node:path'

import type { PackageManagerId } from '../../adapters/package-manager/index'
import { InputError } from '../../errors'
import { loadStackConfig } from '../../intake/config'
import type { DevstackModule } from '../../types/module'
import type { GenerationPlan } from '../../types/plan'
import { CLI_PACKAGE, MANIFEST_PATH, splitModuleEntries, type StackConfig } from '../manifest'
import { buildGenerationPlan } from '../planner/index'

/** A DevStack project as its manifest describes it (buildPlan B12, task 5.6). */
export interface ProjectStack {
  projectDir: string
  manifest: StackConfig
  modules: string[]
  moduleOptions: Record<string, Record<string, unknown>>
  packageManager: PackageManagerId
  packageManagerVersion?: string
}

/** `pnpm@10.26.2` in package.json's `packageManager` field → `10.26.2`. */
async function packageManagerVersionIn(projectDir: string): Promise<string | undefined> {
  try {
    const manifest = JSON.parse(await readFile(path.join(projectDir, 'package.json'), 'utf8')) as {
      packageManager?: unknown
    }
    const field = typeof manifest.packageManager === 'string' ? manifest.packageManager : ''
    return /^[a-z]+@(\d[\w.+-]*)$/.exec(field)?.[1]
  } catch {
    return undefined
  }
}

/** Reads the project's manifest; a folder without one is not a DevStack project. */
export async function readProjectStack(projectDir: string): Promise<ProjectStack> {
  const file = path.join(projectDir, MANIFEST_PATH)
  try {
    await access(file)
  } catch (error: unknown) {
    throw new InputError(
      `${projectDir} is not a DevStack project (no ${MANIFEST_PATH}); run this in a project's root folder.`,
      { cause: error }
    )
  }
  const manifest = await loadStackConfig(file)
  const { ids, options } = splitModuleEntries(manifest.modules)
  const version = manifest.packageManagerVersion ?? (await packageManagerVersionIn(projectDir))
  return {
    projectDir,
    manifest,
    modules: ids,
    moduleOptions: options,
    packageManager: manifest.packageManager ?? 'npm',
    ...(version === undefined ? {} : { packageManagerVersion: version })
  }
}

/**
 * The plan for this project with these modules: same name, settings, depth and package manager
 * as recorded, so the files a module does not touch come out byte for byte the same.
 */
export function planProject(
  stack: ProjectStack,
  modules: readonly string[],
  moduleOptions: Readonly<Record<string, Record<string, unknown>>>,
  registry: Map<string, DevstackModule>
): Promise<GenerationPlan> {
  return buildGenerationPlan({
    projectName: stack.manifest.name,
    projectDir: stack.projectDir,
    selectedModuleNames: [...modules],
    moduleOptions,
    registry,
    packageManager: stack.packageManager,
    ...(stack.packageManagerVersion === undefined
      ? {}
      : { packageManagerVersion: stack.packageManagerVersion }),
    ...(stack.manifest.depth === undefined ? {} : { depth: stack.manifest.depth }),
    ...(stack.manifest.settings === undefined ? {} : { settings: stack.manifest.settings }),
    options: { skipInstall: false, skipGit: true }
  })
}

/** Files from a different CLI version may differ in ways the user did not make. */
export function versionNote(stack: ProjectStack): string | undefined {
  const by = stack.manifest.generatedBy
  if (by === undefined || by.version === CLI_PACKAGE.version) return undefined
  return `This project was generated by ${by.name} ${by.version}; this is ${CLI_PACKAGE.version}. Files that changed between the versions count as your edits and are not overwritten.`
}
